name: .NET

permissions:
  packages: read|write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore --configfile ./nuget.config --ignore-failed-sources

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release

    - name: Pack package
      run: dotnet pack --no-build -c Release ./Saga
      if: ${{ github.ref == 'refs/heads/main' && success() }}
      
    - name: Push to repository
      run: dotnet nuget push "./Saga/bin/Release/*.nupkg" --api-key ${GITHUB_TOKEN} -s github
      if: ${{ github.ref == 'refs/heads/main' && success() }}